language: ruby
cache: bundler
rvm:
  - 2.6.5
  - 2.7.0
git:
  depth: 10

sudo: false

before_install:
  - gem install bundler

before_script: bundle update
script: script/test

os:
  - linux
  - osx

matrix:
  include:
    - script: bundle exec rake rubocop
      rvm: 2.6.5

env:
  -TREE_SITTER_PARSER_DIR=$TRAVIS_BUILD_DIR/test/tree-sitter/fixtures/parsers
